name: InventoryHolder
version: 1.0.0-SNAPSHOT
author: elsiff
main: me.elsiff.inventoryholder.InventoryHolder
commands:
  inventoryholder:
    description: Main command for InventoryHolder.
    usage: /inventoryholder
    aliases: [ih, invh, invholder]
permissions:
  invholder.admin:
    default: op
    description: Player with this permission can use the all commands.
  invholder.load:
    default: op
    description: Player with this permission can load any kits.